# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
sxg:
  html_host: my_domain.com
  cert_url_dirname: ".well-known/sxg-certs"
  forward_request_headers:
    - cf-ipcountry
    - user-agent
  reserved_path: ".sxg"
  respond_debug_info: true
  strip_request_headers: []
  strip_response_headers:
    - set-cookie
    - strict-transport-security
  validity_url_dirname: ".well-known/sxg-validity"

# This section contains config for Cloudflare Workers.
# You may remove it if you are not using Cloudflare workers.
cloudflare:
  # To find Cloudflare account ID and zone ID, refer to this screenshot.
  # https://forum.aapanel.com/d/3914-how-to-get-zone-id-of-cloudflare
  account_id: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  zone_id: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  # This decides which URLs need to be signed by SXG.
  # For the pattern syntax, please refer to Cloudflare's doc.
  # https://developers.cloudflare.com/workers/platform/routes
  routes:
    - "my_domain.com/*"

# This section contains config for Fastly Compute.
# You may remove it if you are not using Fastly Compute.
fastly:
  # To create a service, use the command "fastly service create --type wasm --name=sxg-rs".
  # The service ID will be printed in the console.
  service_id: XXXXXXXXXXXXXXXXXXXXXX
  # To get the base64 encoded private key, use the following command
  # "go run ../credentials/parse_private_key.go <../credentials/privkey.pem".
  private_key_base64: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXU=
