// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use std::io::Result as IoResult;

pub fn write_generated_file(file: &str, content: &str) -> IoResult<()> {
    std::fs::write(
        file,
        format!(
            "# This file is generated by command \"{}\".\n\
             # Do not edit this file. If you would like to customize your config,\n\
             # please edit \"{}\" and re-run the command.\n\
             {}",
            *super::COMMAND,
            super::INPUT_FILE,
            content,
        ),
    )?;
    println!("Successfully wrote config to {}", file);
    Ok(())
}
