name: 'Unit tests for Rust'
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -y
      - working-directory: ./sxg-rs/
        run: cargo test

