name: Unit tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - working-directory: credentials
        run: |
          cargo run -p config-generator -- --target cloudflare --create-dev-cert credentials
          cargo run -p config-generator -- --target fastly
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
  TypeScript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - working-directory: cloudflare_worker/worker
        run: |
          npm install
          npm run build
          npm run test

