name: 'Unit tests'
on: push

jobs:
  test-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - working-directory: ./cloudflare_worker/worker/
        run: |
          npm install
          npm run build
          npm run test

